meta_product_name: "Où est la plage?"
meta_title: "Où est la plage? - Organic wine in a can"
meta_description: "Our wines are produced in France by winegrowers who are passionate about their work and their lands."
meta_image: "rose_front_back_small.png" # should exist in `app/assets/images/`
